### ISSUE TITLE
Would it be possible to add instructions into README about how to integrate with Rubocop?

### ISSUE THREAD

**Issue by lucascaton** [brigade/haml-lint#103]

**Comment by sds** [comment]
Hey @lucascaton,

There's no setup required&mdash;just run `haml-lint` and as long as you have the `RuboCop` linter enabled (which is the default) the Ruby from your HAML files will be passed through to RuboCop.

You can verify this yourself with the following test file:

**`test.haml`**
```haml
- some_unused_variable = 'Hello world'
%p Hello
```

Running `haml-lint test.haml` will result in the following output:
```
test.haml:1 [W] RuboCop: Useless assignment to variable - `some_unused_variable`.
```

Hope that helps.

**Comment by lucascaton** [comment]
@sds Ah, cool!

But what I meant was: is there a way to run it along with Rubocop (without having to run 2 different commands)?

Cheers.

**Comment by sds** [comment]
You could execute both from a Rake task (or via similar approaches).
