### ISSUE TITLE
Add Checkstyle formatter

### ISSUE THREAD

**Issue by swalberg** [brigade/haml-lint#110]
Hi, Rubocop can use a checkstyle output format so that CI systems like Jenkins can pick it up, and I was wondering if there's something similar for this since it's integrated with Rubocop? Checkstyle is similar to JSON, just in XML.

The module that does it is at https://github.com/eitoball/rubocop-checkstyle_formatter but I'm not clear how the integration works.

Thanks,

Sean

**Comment by sds** [comment]
Since `haml-lint` handles its own output, it can't use any custom formatters from RuboCop.

Happy to accept a pull request adding a Checkstyle formatter.

**Comment by swalberg** [comment]
Thanks Shane. I'll see what I can do.

**Comment by sds** [comment]
Implemented in #111. Thanks!
