### ISSUE TITLE
Release 0.16 tag to rubygems.

### ISSUE THREAD

**Issue by aeberlin** [brigade/haml-lint#117]
Please publish to RubyGems! Thanks!

**Comment by aeberlin** [comment]
Guessing you're waiting to finish the rename, but please include that, too.

**Comment by sds** [comment]
Hey @aeberlin,

[HAML-Lint 0.16.0](https://rubygems.org/gems/haml_lint) was pushed to Rubygems in January. Please make sure you are downloading the `haml_lint` gem and not `haml-lint`, as the gem was renamed to follow [proper Rubygems naming conventions](http://guides.rubygems.org/name-your-gem/).

**Comment by aeberlin** [comment]
Ahhhh, I see. Didn't realize you left the old repo. Thanks!

**Comment by sds** [comment]
The old Rubygem was left behind to prevent a situation where an attacker would reclaim the gem name and upload a gem with malicious code. Enough people still use HAML-Lint with the old `haml-lint` gem name in their bundles that it would be irresponsible to completely yank the gem (even if no one uploaded a malicious gem, it would [break many gem files still in use](https://github.com/search?q=%22gem+%27haml-lint%27%22&ref=searchresults&type=Code&utf8=%E2%9C%93)).
