### ISSUE TITLE
Add --auto-gen-config option

### ISSUE THREAD

**Issue by NoahFisher** [brigade/haml-lint#119]
Hi, 

Is there an on-boarding process outlined somewhere? I'm a big fan of the `--auto-gen-config` that rubocop provides especially for the larger projects.  

Thanks!

**Comment by sds** [comment]
Hey @NoahFisher,

There is no such flag at this point in time. Happy to accept a pull request adding one!

**Comment by NoahFisher** [comment]
@sds thanks for the quick response! I'll have a look...
