### ISSUE TITLE
Rubocop integration

### ISSUE THREAD

**Issue by agross** [brigade/haml-lint#125]
From the README:
> it integrates with RuboCop 

I might not be able to see the forest for the trees: What do you mean by "integrate"?

My interpretation of that statement is that you can run haml-lint from inside Rubocop to see Ruby and Haml errors in one place. Is that correct? (I come to this conclusion because there is [rubocop-rspec](https://github.com/nevir/rubocop-rspec) that enhances Rubocop with rspec-specific rules.)

Another interpretation might be that haml-lint respects `.rubocop.yml` and pulls e.g. disabled cops from the file.

Could you please point me in the right direction?

**Comment by maxjacobson** [comment]
It's a bit different from rubocop-rspec. It's a separate command for you to run (`bundle exec haml-lint .` or `bin/haml-lint .`) which inspects haml files instead of ruby files. It borrows the power of RuboCop to inspect the ruby code embedded in the haml files, and then checks for some haml-specific issues.

**Comment by sds** [comment]
Hey @agross,

HAML-Lint is a standalone project which you could run without any connection to RuboCop. However, a major selling point of the HAML-Lint is that you can lint Ruby code that appears in a HAML template with RuboCop using HAML-Lint's [RuboCop linter](https://github.com/brigade/haml-lint/blob/master/lib/haml_lint/linter/rubocop.rb) which runs extracted Ruby code from a HAML file through RuboCop. 

So if you're running HAML-Lint against the following HAML template:

```haml
- unused_variable = :foo
%p Hello World!
```

...it will extract Ruby code looking something like:

```ruby
unused_variable = :foo
```

...and feed that into RuboCop, reporting any issues. The net result being that you get output like:

```
test.haml:1 [W] RuboCop: Useless assignment to variable - `unused_variable`.
```

**Comment by agross** [comment]
Thank you very much, @sds and @maxjacobson! :+1:
