### ISSUE TITLE
Issue with installation of haml-lint

### ISSUE THREAD

**Issue by shmulikt** [brigade/haml-lint#134]
I am trying to run gem install haml-lint -v '0.13.0' and get 404.

ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Not Found 404 (https://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/haml-lint-0.13.0.gemspec.rz)

**Comment by sds** [comment]
Hey @shmulikt,

Please install using `haml_lint`, not `haml-lint`. `haml_lint` matches [RubyGems naming conventions](http://guides.rubygems.org/name-your-gem/).
