### ISSUE TITLE
Progress Reporter?

### ISSUE THREAD

**Issue by mockdeep** [brigade/haml-lint#146]
Would love to have a progress reporter similar to what rubocop provides by default.

**Comment by michaelherold** [comment]
I took a look at implementing this and got pretty far until I got down to testing it on real files. The formatting isn't difficult, but the architectural changes needed for a progress reporter are large.

Currently, Haml-Lint gathers the lint for all of the files up front and then reports on the full results. This would need to be changed in the runner to let the file results be reported as soon as they come in.
