### ISSUE TITLE
RepeatedId linter not clearing list between files

### ISSUE THREAD

**Issue by ValenciaMgmt** [brigade/haml-lint#193]
It seems that the list used by RepeatedId is not being cleared after each file is checked. I have different tabs that get activated based on anchor tags, and many different models in my Rails app have the same tabs.

Using version 0.23.0:

```
echo "#whatever Div with id attribute" > repeated_ids_1.html.haml
echo "#whatever Div with id attribute" > repeated_ids_2.html.haml
haml-lint .
```

output:

```
repeated_id_2.html.haml:1 [E] RepeatedId: Do not repeat id "#whatever" on the page
repeated_id_2.html.haml:1 [E] RepeatedId: Do not repeat id "#whatever" on the page

2 files inspected, 2 lints detected
```

**Comment by michaelherold** [comment]
Good catch. I thought we were instantiating a new linter for every file but that doesn't appear to be the case. I'll patch that up.
