### ISSUE TITLE
haml-lint_todo is not properly generated

### ISSUE THREAD

**Issue by Ana06** [brigade/haml-lint#207]
`.haml-lint_todo.yml` is completely ignored. All the offences keep appearing.

- Haml-Lint version: 0.23.2 (current master: 59e084435460fbf2d01cf32552d7201bc9ece6d9)
- Haml version: 4.0.7
- RuboCop version: 0.47.1
- Ruby version: 2.4.0

**Comment by trotzig** [comment]
Did you add it to your .haml-lint.yml config file in an `inherits_from`?

**Comment by Ana06** [comment]
Yes! I found out what the problem is.

The `auto-gen-config` is not working properly:
- it doesn't add `linters:` on top
- `Exclude:` should be `exclude:` without capital letters.

I'll try to fix it and open a PR :wink:

**Comment by michaelherold** [comment]
Oy vey. I apparently can't test properly.

I'll take a look at this one tonight. Apologies for the issues!

**Comment by Ana06** [comment]
I didn't open a PR for that as it is already included in https://github.com/michaelherold/haml-lint/commit/9cf6c4e21f9844f0b5c4e88c3d365875a15b5442
