### ISSUE TITLE
Proposal: Add rule for max lines in a haml view

### ISSUE THREAD

**Issue by andyw8** [brigade/haml-lint#213]
A view with a large number of lines is hard to manage, and should probably be split into separate partials, or have some logic extracted out, e.g. into a helpers, presenters, decorators, etc.

I'd suggest 100 lines as a starting point.

Would you accept a PR which added this?

**Comment by trotzig** [comment]
Absolutely, this sounds very reasonable.

**Comment by michaelherold** [comment]
I really like this idea.

It feels more like the set of metrics checks that RuboCop has while the others are style checks. I wonder if it would be useful (yet) to start namespacing linters by their types (i.e. `Style/LineLength` vs `Metrics/ViewLength`)? It's probably too early for that, but it's definitely something that would prove useful down the road.

**Comment by andyw8** [comment]
Opened as https://github.com/brigade/haml-lint/pull/237
