### ISSUE TITLE
Fail fast option not using fail level in version 0.24

### ISSUE THREAD

**Issue by agrimm** [brigade/haml-lint#215]
When using `--fail-fast` and `--fail-level` together, it still fails fast on a warning when I'm only checking for errors. I'm using version 0.24, which I assume was released subsequently to #182 . Should this be happening?

    Andrews-Air:foo agrimm$ bundle exec haml-lint app/views/ --fail-fast --fail-level error
    warning: parser/current is loading parser/ruby22, which recognizes
    warning: 2.2.6-compliant syntax, but you are running 2.2.5.
    warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
    app/views/foo/_bar.html.haml:24 [W] ConsecutiveComments: 2 consecutive comments can be merged into one

    1 file inspected, 1 lint detected
    Andrews-Air:foo agrimm$ bundle exec haml-lint --version
    warning: parser/current is loading parser/ruby22, which recognizes
    warning: 2.2.6-compliant syntax, but you are running 2.2.5.
    warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
    haml-lint 0.24.0

**Comment by michaelherold** [comment]
That's a bug. I can look into it unless you want to try your hand at a PR.

**Comment by agrimm** [comment]
I don't intend trying to create a bugfix for this.
