### ISSUE TITLE
Fail level syntax doesn't allow single letters

### ISSUE THREAD

**Issue by agrimm** [brigade/haml-lint#216]
`bundle exec haml-lint --fail-level E` isn't regarded as valid. You have to specify "error", and the requirement that you have to use a full word isn't mentioned in the output of `bundle exec haml-lint --help`.

This is the opposite of rubocop, which allows single letters, and mentions what letters are allowed.

Possible solutions: either allow single letters, specify in the help that you have to use full words, or list what the allowed fail levels are.

**Comment by michaelherold** [comment]
I honestly didn't know that you could pass a single letter to Rubocop. TIL about this feature.

**Comment by trotzig** [comment]
Thanks for reporting this @agrimm. I'm okay with a simple update to the docs/cli output to make this clearer. Would you mind preparing a PR?

**Comment by agrimm** [comment]
Sure.
