### ISSUE TITLE
disable linters in the todo file

### ISSUE THREAD

**Issue by Ana06** [brigade/haml-lint#223]
We should disable instead of exclude the files with offenses when there are many files affected when autogenerating `.haml-lint_todo.yml`. It looks horrible when you have a list of 100 files. :confounded: 

This is something Rubocop does. They even allow you to set the maximum of files. So it would be nice to do it here in a similar way.

**Comment by Ana06** [comment]
If we agree we want this, I can work on it and send a PR. :wink:

**Comment by trotzig** [comment]
What would be a good threshold for doing this would you think? 

Also, I'd be interested in hearing @michaelherold's input here.

**Comment by Ana06** [comment]
@trotzig 
> What would be a good threshold for doing this would you think?

[Rubocop](https://github.com/bbatsov/rubocop/blob/master/manual/configuration.md#automatically-generated-configuration) default threshold is 15, so I think we could use 15 too.

**Comment by trotzig** [comment]
That sounds good to me.

**Comment by michaelherold** [comment]
I'm for this. 👍

I think the 15 limit makes sense here too.
