### ISSUE TITLE
Suggestion: Add rule to detect inline styles

### ISSUE THREAD

**Issue by andyw8** [brigade/haml-lint#226]
In most cases it's preferable define CSS rules in a stylesheet rather than an inline `style` attribute.

Does this seem in scope for haml-lint?

**Comment by trotzig** [comment]
Definitely! Is this something you'd be interested taking on? If you need guidance, [here's an example of a good commit adding a new linter](https://github.com/brigade/haml-lint/commit/73d80994dce9c7b34bb78fb363ca59929d68bf53).

**Comment by andyw8** [comment]
Thanks, I'll try find some time.
