### ISSUE TITLE
rubocop linters use Rubocop config file

### ISSUE THREAD

**Issue by Ana06** [brigade/haml-lint#235]
If you have Rubocop and Haml-Lint in the same project I think it makes a lot of sense that Haml-Lint rubocop linter use Rubocop configuration. Code consistency is one of the main reason to use Rubocop and Haml-Lint and having two different configuration options goes completely against that.

**Comment by sds** [comment]
Hey @Ana06,

This should already be the behavior. HAML-Lint will extract the Ruby code from a HAML template and run RuboCop on it, passing a file path that ensures any `.rubocop.yml` configuration in the same directory as that HAML template will be used.

Can you provide a reproducible case and explain what you expect versus what you observe? Bear in mind that if you have path-based inclusions/exclusions in your `.rubocop.yml` that they won't match what you're expecting, as RuboCop will think the path ends in `.haml`, not `.rb`.

**Comment by Ana06** [comment]
Sorry, I meant something else but got confused while writing. :confounded: 

I'll close this and open a new issue. :wink:
