### ISSUE TITLE
InstanceVariables is not added to the todo file

### ISSUE THREAD

**Issue by Ana06** [brigade/haml-lint#252]
If after running `haml-lint --auto-gen-config` you run `haml-lint` if finds offenses of the `InstanceVariables` cop. So this cop is not added to the `haml-lint_todo.yml` file.

I am using `haml-lint 0.24.0`.

**Comment by Ana06** [comment]
I just checked and this is working in `haml-lint 0.26.0`

**Comment by Ana06** [comment]
Although this may be in the release notes.... :confused:

**Comment by Ana06** [comment]
Although this may be in the release notes and it is not.... :confused:

**Comment by michaelherold** [comment]
Can you attach your `.haml-lint.yml` and your `haml-lint_todo.yml`?

**Comment by Ana06** [comment]
the `.haml-lint.yml` just include the `haml-lint_todo.yml` file. And `haml-lint_todo.yml` has all the offenses except the ones of this cop.

This is actually not that important, as it is working in the last version.

**Comment by Ana06** [comment]
@michaelherold is this already fixed? :thinking:

**Comment by michaelherold** [comment]
I haven't had a chance to look at this, so I'm not sure if it's working or not.

**Comment by sds** [comment]
I closed this because it seemed to be a duplicate of #256. If I'm mistaken, feel free to reopen.

**Comment by Ana06** [comment]
I think it is not, but I would double check before you reopen it. :wink:
