### ISSUE TITLE
ViewLength find in last release more offenses

### ISSUE THREAD

**Issue by Ana06** [brigade/haml-lint#253]
`ViewLength` linter find offenses that were not find before when updating from `0.24.0` to `0.26.0`. It is completely fine as there is actually an offense and it should complain, but in the release notes there is nothing about this linter. Was something modified there? :confused:

**Comment by andyw8** [comment]
Sorry, I added this in https://github.com/brigade/haml-lint/pull/237 but neglected to update the changelog, and guess @trotzig didn't notice when merging.
