### ISSUE TITLE
RuboCop: Final newline missing error

### ISSUE THREAD

**Issue by mwraich** [brigade/haml-lint#254]
Using haml-lint 0.26.0 I got the RuboCop: Final newline missing error. I've isolated the error to appear from a simple haml file with a %table. 
ex. 
```
#some_report/show.html.haml
%table
```

^That alone creates the above error. I've run the above in 0.25 and it passes fine, so the issue must have been introduced in 0.26.

**Comment by michaelherold** [comment]
I can't reproduce this on either v0.25.0 or v0.26.0. Could you see if you can write a test to reproduce?

**Comment by wintersolutions** [comment]
Hi, I had the same issue and discovered that I had the following entry in my `.haml-lint.yml`:

```
linters:
  RuboCop:
    ignored_cops:
      - Style/TrailingBlankLines
```

Which was renamed to `Layout/TrailingBlankLines` by rubocop.

Since I had it in the ignores already I guess it never worked for me in the first place.

**Comment by mwraich** [comment]
@wintersolutions Thanks, that looked like it fixed it.
