### ISSUE TITLE
Rubocop's Layout/AlignHash needs to be ignored

### ISSUE THREAD

**Issue by coolo** [brigade/haml-lint#286]
I'm trying to enable that [rubocop for our project](https://github.com/openSUSE/open-build-service/pull/6177), but haml_lint barfs on basically well aligned parameters.

the haml is 
```
  $('#modal').html("#{escape_javascript(render(partial: 'submit_request_dialog',
                                               locals: { project: @project, package: @package,
                                               revision: @revision, target_project: @tprj, target_package: @tpkg,
                                               description: @description, cleanup_source: @cleanup_source }))}")
```

The extracted ruby looks like this:
```
escape_javascript(render(partial: 'submit_request_dialog',
                                             locals: { project: @project, package: @package,
                                             revision: @revision, target_project: @tprj, target_package: @tpkg,
                                             description: @description, cleanup_source: @cleanup_source }))
```

And so I get a 
[W] RuboCop: Layout/AlignHash: Align the elements of a hash literal if they span more than one line.

which I can't fix without reverse engineering haml_lint.

So please add Layout/AlignHash to the default ignored_cops - for now I had to copy your list of ignored_cops into our config, which is not exactly ideal

**Comment by sds** [comment]
Happy to merge a pull request, @coolo. Thanks!

**Comment by coolo** [comment]
There you go: https://github.com/brigade/haml-lint/pull/290

**Comment by sds** [comment]
Thanks!
