### ISSUE TITLE
Add a fail-fast option

### ISSUE THREAD

**Issue by shaneog** [brigade/haml-lint#80]
My team like to run linters as part of our builds, and consider failing linting to be a failed build. 

It would be great to add a `--fail-fast` option which would fail immediately on the first linting failure found.

**Comment by sds** [comment]
I'm ok with this idea, but I'm curious how much time you're saving. If you already have asynchronous builds running, I doubt saving 10-30 seconds over running `haml-lint` on your entire project and seeing _all_ failures is that useful when you only get the first error returned.

It's also possible I'm misunderstanding what you mean by "build". If you use `haml-lint` in a pre-commit git hook, I could perhaps see a greater case for this, but again wouldn't you want to know about all the problems so you don't have to deal with the turnaround time of implementing a fix and then re-running `haml-lint` for each warning you receive?

**Comment by michaelherold** [comment]
Much like my comment [here](https://github.com/brigade/haml-lint/issues/146#issuecomment-280551492), this feature would require changing the way the runner constructs the result set.
