### ISSUE TITLE
autocorrection ability

### ISSUE THREAD

**Issue by stereodenis** [brigade/haml-lint#88]
we need autocorrecting, for example `haml-lint app/views -a` like rubocop

**Comment by sds** [comment]
Hey @stereodenis, thanks for suggesting ways we can improve `haml-lint`.

Adding auto-correcting functionality simply isn't practical. RuboCop enjoyed the benefit of using the powerful `parser` gem, which makes it trivial to rewrite code by modifying the abstract syntax tree.

The `haml` gem's parser comes nowhere close to this level of flexibility, and the situation is further complicated by the fact that there are two languages here: Ruby _and_ HAML, so we'd have to leverage RuboCop's autocorrecting as well build our own mutable syntax tree representation for HAML.

It's certainly possible but would be a huge undertaking in itself, so unless someone comes along and implements it you won't be seeing this feature in `haml-lint`.
