### ISSUE TITLE
Undefined method join for nil:NilClass

### ISSUE THREAD

**Issue by dylangrafmyre** [brigade/haml-lint#89]
(feature/linting) ✗ haml-lint app/**/*.html.haml                                                                              70 ↵ ✹ ✭ [8:36:04]
undefined method `join' for nil:NilClass
/Users/dylan/.rvm/gems/ruby-2.2.2@bpos/gems/haml_lint-0.15.0/lib/haml_lint/tree/node.rb:56:in `source_code'
/Users/dylan/.rvm/gems/ruby-2.2.2@bpos/gems/haml_lint-0.15.0/lib/haml_lint/tree/tag_node.rb:91:in `attributes_source'
/Users/dylan/.rvm/gems/ruby-2.2.2@bpos/gems/haml_lint-0.15.0/lib/haml_lint/tree/tag_node.rb:65:in `static_attributes_source'
/Users/dylan/.rvm/gems/ruby-2.2.2@bpos/gems/haml_lint-0.15.0/lib/haml_lint/linter/classes_before_ids.rb:14:in `visit_tag'
/Users/dylan/.rvm/gems/ruby-2.2.2@bpos/gems/haml_lint-0.15.0/lib/haml_lint/haml_visitor.rb:18:in `visit'
/Users/dylan/.rvm/gems/ruby-2.2.2@bpos/gems/haml_lint-0.15.0/lib/haml_lint/haml_visitor.rb:27:in `block in visit_children'
/Users/dylan/.rvm/gems/ruby-2.2.2@bpos/gems/haml_lint-0.15.0/lib/haml_lint/haml_visitor.rb:27:in `each'
/Users/dylan/.rvm/gems/ruby-2.2.2@bpos/gems/haml_lint-0.15.0/lib/haml_lint/haml_visitor.rb:27:in `visit_children'
/Users/dylan/.rvm/gems/ruby-2.2.2@bpos/gems/haml_lint-0.15.0/lib/haml_lint/haml_visitor.rb:23:in `visit'
/Users/dylan/.rvm/gems/ruby-2.2.2@bpos/gems/haml_lint-0.15.0/lib/haml_lint/haml_visitor.rb:27:in `block in visit_children'
/Users/dylan/.rvm/gems/ruby-2.2.2@bpos/gems/haml_lint-0.15.0/lib/haml_lint/haml_visitor.rb:27:in `each'
/Users/dylan/.rvm/gems/ruby-2.2.2@bpos/gems/haml_lint-0.15.0/lib/haml_lint/haml_visitor.rb:27:in `visit_children'
/Users/dylan/.rvm/gems/ruby-2.2.2@bpos/gems/haml_lint-0.15.0/lib/haml_lint/haml_visitor.rb:23:in `visit'
/Users/dylan/.rvm/gems/ruby-2.2.2@bpos/gems/haml_lint-0.15.0/lib/haml_lint/linter.rb:28:in `run'
/Users/dylan/.rvm/gems/ruby-2.2.2@bpos/gems/haml_lint-0.15.0/lib/haml_lint/runner.rb:58:in `block in collect_lints'
/Users/dylan/.rvm/gems/ruby-2.2.2@bpos/gems/haml_lint-0.15.0/lib/haml_lint/runner.rb:57:in `map'
/Users/dylan/.rvm/gems/ruby-2.2.2@bpos/gems/haml_lint-0.15.0/lib/haml_lint/runner.rb:57:in `collect_lints'
/Users/dylan/.rvm/gems/ruby-2.2.2@bpos/gems/haml_lint-0.15.0/lib/haml_lint/runner.rb:21:in `block in run'
/Users/dylan/.rvm/gems/ruby-2.2.2@bpos/gems/haml_lint-0.15.0/lib/haml_lint/runner.rb:20:in `map'
/Users/dylan/.rvm/gems/ruby-2.2.2@bpos/gems/haml_lint-0.15.0/lib/haml_lint/runner.rb:20:in `run'
/Users/dylan/.rvm/gems/ruby-2.2.2@bpos/gems/haml_lint-0.15.0/lib/haml_lint/cli.rb:82:in `scan_for_lints'
/Users/dylan/.rvm/gems/ruby-2.2.2@bpos/gems/haml_lint-0.15.0/lib/haml_lint/cli.rb:51:in `act_on_options'
/Users/dylan/.rvm/gems/ruby-2.2.2@bpos/gems/haml_lint-0.15.0/lib/haml_lint/cli.rb:23:in `run'
/Users/dylan/.rvm/gems/ruby-2.2.2@bpos/gems/haml_lint-0.15.0/bin/haml-lint:7:in `<top (required)>'
/Users/dylan/.rvm/gems/ruby-2.2.2@bpos/bin/haml-lint:23:in `load'
/Users/dylan/.rvm/gems/ruby-2.2.2@bpos/bin/haml-lint:23:in `<main>'
/Users/dylan/.rvm/gems/ruby-2.2.2@bpos/bin/ruby_executable_hooks:15:in `eval'
/Users/dylan/.rvm/gems/ruby-2.2.2@bpos/bin/ruby_executable_hooks:15:in `<main>'
Report this bug at https://github.com/brigade/haml-lint/issues

To help fix this issue, please include:
- The above stack trace
- Haml-Lint version: 0.15.0
- Haml version: 4.0.6
- RuboCop version: 0.32.1
- Ruby version: 2.2.2

Any ideas? I can run individual files but anything else fails. 
haml-lint app/**/*.html.haml
haml-lint app/views

Thank you so much!

**Comment by dylangrafmyre** [comment]
Hello, 

You can close this issue. I tracked it down to a couple files, and fixed the issues.

Thanks for the great linting tool!

Dylan

**Comment by sds** [comment]
Hey @dylangrafmyre,

Sorry for the delay in response. Do you happen to have a small snippet of source code that reproduces the issue which you can post here? `haml-lint` shouldn't crash in this way, and having a reproducible example would be instrumental in fixing the problem.

**Comment by dylangrafmyre** [comment]
@sds, sorry for my late reply too :)

This was one of the files: 
```haml
- classes = ["main", @container_class]
- if @container_full_width
  - classes << "container-fluid"
  = yield
- else
  - classes << "container"
  %div{:class => classes, :id => @container_id}
    = yield
```

**Comment by sds** [comment]
Hey @dylangrafmyre, I'm not able to reproduce the issue with the snippet you've provided. Perhaps there are some hidden characters that are getting lost in translation.

What happens if you copy/paste the snippet above from GitHub into a single file and run `haml-lint` against that file? Does it still fail with the error you're seeing?

**Comment by dylangrafmyre** [comment]
I pulled a older version of the file from another branch. Yes, you are
right. There was some hidden line separators that once, I fixed with the
IDE, the haml-lint issue stopped.

Thanks for looking into this issue!

Aloha,
dylan[image: Inline image 1]
