### ISSUE TITLE
undefined method `load_file' for Psych:Module

### ISSUE THREAD

**Issue by romanblanco** [brigade/haml-lint#90]
Hello guys, I'm having troubles with running haml-lint. Here is log:

    $ haml-lint .
    warning: parser/current is loading parser/ruby22, which recognizes
    warning: 2.2.3-compliant syntax, but you are running 2.2.2.
    undefined method `load_file' for Psych:Module
    /home/rblanco/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/haml_lint-0.15.0/lib/haml_lint/configuration_loader.rb:62:in `load_from_file'
    /home/rblanco/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/haml_lint-0.15.0/lib/haml_lint/configuration_loader.rb:34:in `load_file'
    /home/rblanco/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/haml_lint-0.15.0/lib/haml_lint/configuration_loader.rb:18:in `load_applicable_config'
    /home/rblanco/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/haml_lint-0.15.0/lib/haml_lint/runner.rb:40:in `load_applicable_config'
    /home/rblanco/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/haml_lint-0.15.0/lib/haml_lint/runner.rb:15:in `run'
    /home/rblanco/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/haml_lint-0.15.0/lib/haml_lint/cli.rb:82:in `scan_for_lints'
    /home/rblanco/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/haml_lint-0.15.0/lib/haml_lint/cli.rb:51:in `act_on_options'
    /home/rblanco/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/haml_lint-0.15.0/lib/haml_lint/cli.rb:23:in `run'
    /home/rblanco/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/haml_lint-0.15.0/bin/haml-lint:7:in `<top (required)>'
    /home/rblanco/.rbenv/versions/2.2.2/bin/haml-lint:23:in `load'
    /home/rblanco/.rbenv/versions/2.2.2/bin/haml-lint:23:in `<main>'
    Report this bug at https://github.com/brigade/haml-lint/issues

    To help fix this issue, please include:
    - The above stack trace
    - Haml-Lint version: 0.15.0
    - Haml version: 4.0.6
    - RuboCop version: 0.32.1
    - Ruby version: 2.2.2

Do you have any idea, what could be wrong?

**Comment by sds** [comment]
Hey @romanblanco,

This issue is outside the control of `haml-lint` and has to do with the version of the `psych` gem installed on your system. From https://github.com/bbatsov/rubocop/issues/1510 it looks like the solution is to either run `gem update --system` or uninstall the `psych` gem on your system. 

Hope that helps!
