### ISSUE TITLE
Cannot exclude file from linter

### ISSUE THREAD

**Issue by shaneog** [brigade/haml-lint#98]
Possible duplicate of #78.

I can't exlude a file from a certain linter. 
I've created a gist with the files I'm using to test: https://gist.github.com/shaneog/45cb88344d44a868a485

```shell
$ haml-lint -c .haml-lint.yml *
_media.html.haml:6 [W] LineLength: Line is too long. [159/110]
```

```shell
$ haml-lint --version
haml-lint 0.13.0
```

**Comment by AlekseyGR** [comment]
I have the same problem

**Comment by sds** [comment]
Hey @shaneog,

I can't reproduce this with the latest version of `haml-lint` (0.15.2 at time of writing). Upgrading should fix whatever issue you're seeing.

**Comment by shaneog** [comment]
That version is not pushed to [Rubygems](https://rubygems.org/gems/haml-lint) :disappointed:

**Comment by shaneog** [comment]
Ignore me, I see it's been renamed to `haml_lint`
