### ISSUE TITLE
Ignore some specific ruby-styled comments (i18n)

### ISSUE THREAD

**Issue by skateman** [brigade/haml-lint#99]
Hi!

Is it somehow possible to not mark some specific ruby comments as errors?
We're trying to use [gettext_i18n_rails'](https://github.com/grosser/gettext_i18n_rails) `rake gettext:find` to extract the strings to translate and the HAML engine sends further only the ruby-styled `- #` comments to the parser. The problem is that `haml-lint` treats those comments as erros, which is a great feature, but it would be good to ignore these errors if they're beginning with e.g. `- # TRANSLATORS: `.

Are you planning something similar or would you accept a pull request which implements this feature?

**Comment by sds** [comment]
Hey @skateman,

I'm not familiar with this gem, so I don't think I understand what you're asking for. Why are these comments necessary at all? Quickly searching the [README](https://github.com/grosser/gettext_i18n_rails/blob/v1.3.0/Readme.md) doesn't show any need for comments that I see.

Is there a reason you couldn't write comments as proper HAML comments? (notice the lack of space after the `-`):
```haml
-# TRANSLATORS: 
```

**Comment by sds** [comment]
Closing due to lack of response.
